enum Mutations {
  SET_USER_AND_SESSION = "SET_USER_AND_SESSION",
  ADD_MARKED_PROJECT = "ADD_MARKED_PROJECT",
  RM_MARKED_PROJECT = "RM_MARKED_PROJECT",
  SET_SELECTED_PROJECTS = "SET_SELECTED_PROJECTS",
}

export default Mutations;
