enum Mutations {
  SET_USER_AND_SESSION = "SET_USER_AND_SESSION",
  ADD_MARKED_PROJECT = "ADD_MARKED_PROJECT",
  RM_MARKED_PROJECT = "RM_MARKED_PROJECT",
  SET_SELECTED_PROJECTS = "SET_SELECTED_PROJECTS",
  SET_SELECTION_COMMENT = "SET_SELECTION_COMMAND",
  NEW_PROJECT = "NEW_PROJECT",
  EDIT_PROJECT = "EDIT_PROJECT",
  RM_PROJECT = "RM_PROJECT",
}

export default Mutations;
