enum Mutations {
  SET_PROJECTS_AND_SESSIONS = "SET_PROJECTS_AND_SESSIONS",
  SET_USER = "SET_USER",
  SET_STAGED_SELECTIONS = "SET_STAGED_SELECTIONS",
  SET_IS_WORKING = "SET_IS_WORKING",
  SET_ERROR = "SET_ERROR",
}

export default Mutations;
