[profile.dev]
codegen-units = 4

[workspace]
members = [
  "lib/",
  "codegen/",
  "contrib/",
  "examples/cookies",
  "examples/errors",
  "examples/form_validation",
  "examples/hello_person",
  "examples/query_params",
  "examples/hello_world",
  "examples/manual_routes",
  "examples/optional_redirect",
  "examples/redirect",
  "examples/static_files",
  "examples/todo",
  "examples/content_types",
  "examples/ranking",
  "examples/testing",
  "examples/request_guard",
  "examples/stream",
  "examples/json",
  "examples/msgpack",
  "examples/handlebars_templates",
  "examples/form_kitchen_sink",
  "examples/config",
  "examples/raw_upload",
  "examples/pastebin",
  "examples/state",
  "examples/managed_queue",
  "examples/uuid",
  "examples/session",
  "examples/raw_sqlite",
  "examples/tls",
  "examples/fairings",
]
